import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case vietnamese = "vi"

    var id: String { rawValue }
    var title: String {
        switch self {
        case .english: "English"
        case .vietnamese: "Tiếng Việt"
        }
    }
}

final class LanguageSettings: ObservableObject {
    static let shared = LanguageSettings()
    private static let storageKey = "appLanguage"

    @Published var selection: AppLanguage {
        didSet { UserDefaults.standard.set(selection.rawValue, forKey: Self.storageKey) }
    }

    private init() {
        selection = AppLanguage(rawValue: UserDefaults.standard.string(forKey: Self.storageKey) ?? "") ?? .english
    }
}

enum L10n {
    static func tr(_ vietnamese: String) -> String {
        guard UserDefaults.standard.string(forKey: "appLanguage") != AppLanguage.vietnamese.rawValue else { return vietnamese }
        return english[vietnamese] ?? vietnamese
    }

    static func format(_ vietnamese: String, _ arguments: CVarArg...) -> String {
        let locale = Locale(identifier: UserDefaults.standard.string(forKey: "appLanguage") ?? "en")
        return String(format: tr(vietnamese), locale: locale, arguments: arguments)
    }

    private static let english: [String: String] = [
        "Chung": "General",
        "Ngôn ngữ": "Language",
        "Tiếng Anh là ngôn ngữ mặc định. Có thể đổi lại bất cứ lúc nào.": "English is the default language. You can switch at any time.",
        "10 giây": "10 seconds",
        "3 giây": "3 seconds",
        "5 giây": "5 seconds",
        "Bút vẽ": "Pen",
        "CHẾ ĐỘ CHỤP": "CAPTURE MODE",
        "Che kín": "Solid cover",
        "Chưa chọn thư mục": "No folder selected",
        "Chưa có ảnh": "No image",
        "Chưa có ảnh gần đây": "No recent captures",
        "Chưa kết nối Google Drive": "Google Drive not connected",
        "Chỉ hiện thumbnail": "Show thumbnail only",
        "Chỉnh sửa": "Edit",
        "Chỉnh sửa ảnh gần nhất": "Edit latest capture",
        "Chọn": "Select",
        "Chọn một cửa sổ đang mở": "Select an open window",
        "Chọn một thao tác để bắt đầu": "Choose an action to get started",
        "Chọn thư mục…": "Choose folder…",
        "Chọn vùng": "Select area",
        "Chụp cuộn": "Scrolling capture",
        "Chụp cửa sổ": "Capture window",
        "Chụp toàn bộ màn hình hiện tại": "Capture the entire current screen",
        "Chụp toàn màn hình": "Capture full screen",
        "Chụp và sao chép chữ": "Capture and copy text",
        "Chụp vùng chọn": "Capture area",
        "Chụp ảnh": "Capture",
        "Chụp, lưu và quyền macOS": "Capture, saving, and macOS permissions",
        "Chữ": "Text",
        "Client ID không hợp lệ. Hãy dùng OAuth Client ID loại Desktop app.": "Invalid Client ID. Use a Desktop app OAuth Client ID.",
        "CÀI ĐẶT": "SETTINGS",
        "CÔNG CỤ": "TOOLS",
        "Cài đặt…": "Settings…",
        "Cắt ảnh": "Crop",
        "Cửa sổ": "Window",
        "Dùng phím thay thế": "Use alternate shortcuts",
        "Dùng thư mục này": "Use this folder",
        "Ghi màn hình": "Screen Recording",
        "Google trả về dữ liệu không hợp lệ. Hãy thử lại.": "Google returned an invalid response. Try again.",
        "Hiện con trỏ khi chụp toàn màn hình": "Show pointer in full-screen captures",
        "Hoàn tác": "Undo",
        "Hành động mặc định": "Default action",
        "Hãy chọn thư mục Google Drive trước khi tải ảnh lên.": "Choose a Google Drive folder before uploading.",
        "Hãy chọn thư mục lưu trong Cài đặt trước.": "Choose a save folder in Settings first.",
        "Hãy lưu OAuth Client ID trong Cài đặt Google Drive trước.": "Save an OAuth Client ID in Google Drive settings first.",
        "Hãy đăng nhập Google và chọn thư mục Drive trước.": "Sign in to Google and choose a Drive folder first.",
        "Hình chữ nhật": "Rectangle",
        "Hình elip": "Ellipse",
        "Hẹn giờ chụp": "Capture delay",
        "Hủy": "Cancel",
        "Không hẹn giờ": "No delay",
        "Không thể chụp màn hình. Hãy thử lại khi màn hình đang mở khóa.": "Could not capture the screen. Try again while the screen is unlocked.",
        "Không thể sao chép ảnh vào clipboard": "Could not copy the image to the clipboard",
        "Không thể đọc ảnh đã chụp": "Could not read the captured image",
        "Không tìm thấy chữ trong ảnh": "No text found in the image",
        "Khởi động lại Sharedee Tools": "Restart Sharedee Tools",
        "Kéo để chọn phần màn hình cần chụp": "Drag to select an area of the screen",
        "Kết nối Google": "Connect Google",
        "Kết nối Google Drive": "Connect Google Drive",
        "Liên kết phải là URL thư mục trên drive.google.com.": "The link must be a folder URL on drive.google.com.",
        "Làm lại": "Redo",
        "Làm mờ": "Blur",
        "Lưu": "Save",
        "Lưu Client ID": "Save Client ID",
        "Lưu vào thư mục trên Mac": "Save to a folder on Mac",
        "Lưu ảnh": "Save image",
        "Màu": "Color",
        "Mũi tên": "Arrow",
        "Mở Sharedee Tools": "Open Sharedee Tools",
        "Mở trên Drive": "Open in Drive",
        "Mở ảnh…": "Open image…",
        "Ngắt kết nối": "Disconnect",
        "Nhấn tổ hợp…": "Press shortcut…",
        "Nhấp vào ô rồi nhấn tổ hợp mới. Phím tắt hoạt động trong mọi ứng dụng khi Sharedee Tools đang chạy.": "Click a shortcut field and press a new key combination. Shortcuts work in every app while Sharedee Tools is running.",
        "Nhận dạng chữ và đưa vào clipboard": "Recognize text and copy it to the clipboard",
        "Nhập chữ": "Enter text",
        "Nút Lưu sẽ dùng thư mục này. Nếu chưa chọn, app sẽ hỏi nơi lưu.": "Save uses this folder. If none is selected, the app asks where to save.",
        "Nếu trùng với phím của macOS hoặc ứng dụng khác, hãy đổi tổ hợp hoặc dùng bộ phím thay thế.": "If a shortcut conflicts with macOS or another app, change it or use the alternate set.",
        "Nội dung chữ": "Text content",
        "PHÍM TẮT": "SHORTCUT",
        "Phím tắt": "Shortcuts",
        "Phím tắt đang được macOS hoặc app khác sử dụng.": "The shortcut is already used by macOS or another app.",
        "Quyền macOS": "macOS permissions",
        "Sao chép": "Copy",
        "Sao chép vào clipboard": "Copy to clipboard",
        "Sao chép ảnh gần nhất": "Copy latest capture",
        "Sau khi bật quyền Ghi màn hình, khởi động lại app một lần để macOS áp dụng quyền mới.": "After enabling Screen Recording, restart the app once so macOS can apply the permission.",
        "Sau khi chụp": "After capture",
        "Sharedee Tools chưa có quyền Ghi màn hình. Hãy bật quyền cho Sharedee Tools trong Cài đặt hệ thống.": "Sharedee Tools needs Screen Recording permission. Enable it in System Settings.",
        "Sẵn sàng chụp": "Ready to capture",
        "Thoát Sharedee Tools": "Quit Sharedee Tools",
        "Thumbnail vẫn hiện để bạn chọn thao tác khác cho từng ảnh.": "Thumbnails still appear so you can choose another action for each capture.",
        "Thư mục Drive đã chọn không cho phép thêm tệp.": "The selected Drive folder does not allow new files.",
        "Thư mục lưu trên Mac": "Save folder on Mac",
        "Thư mục tải ảnh lên": "Upload folder",
        "Toàn màn hình": "Full screen",
        "Trợ năng": "Accessibility",
        "Tài khoản và thư mục tải lên": "Account and upload folder",
        "Tô sáng": "Highlight",
        "Tải lên Drive": "Upload to Drive",
        "Tải lên Google Drive": "Upload to Google Drive",
        "Tổ hợp này đã dùng cho một tác vụ khác.": "This shortcut is already assigned to another action.",
        "Xóa": "Delete",
        "Xóa Client ID": "Remove Client ID",
        "Đang chụp cuộn…": "Capturing scrolling content…",
        "Đang mở Google để chọn thư mục…": "Opening Google to choose a folder…",
        "Đang mở Google để đăng nhập…": "Opening Google sign-in…",
        "Đang nhận dạng chữ…": "Recognizing text…",
        "Đang tải ảnh lên Google Drive…": "Uploading image to Google Drive…",
        "Điều khiển từ mọi ứng dụng": "Control from any app",
        "Đã cấp quyền Ghi màn hình. Hãy khởi động lại Sharedee Tools để quyền có hiệu lực.": "Screen Recording permission was granted. Restart Sharedee Tools to apply it.",
        "Đã di chuyển chú thích": "Annotation moved",
        "Đã hoàn tác": "Undone",
        "Đã hủy chụp ảnh": "Capture cancelled",
        "Đã hủy kết nối Google Drive": "Google Drive connection cancelled",
        "Đã hủy kết nối Google Drive.": "Google Drive connection cancelled.",
        "Đã kết nối Google Drive": "Google Drive connected",
        "Đã làm lại": "Redone",
        "Đã lưu Client ID trong Keychain": "Client ID saved in Keychain",
        "Đã ngắt kết nối Google Drive": "Google Drive disconnected",
        "Đã sao chép chữ nhận dạng vào clipboard": "Recognized text copied to clipboard",
        "Đã sao chép ảnh vào clipboard": "Image copied to clipboard",
        "Đã sửa chữ": "Text updated",
        "Đã xóa Client ID đã lưu": "Saved Client ID removed",
        "Đã xóa chú thích": "Annotation deleted",
        "Đóng": "Close",
        "Đóng cửa sổ chỉnh sửa": "Close editor",
        "Đóng thumbnail": "Close thumbnail",
        "Đăng nhập Google đã hết thời gian chờ. Hãy thử lại.": "Google sign-in timed out. Try again.",
        "Đặt lại phím tắt mặc định": "Reset default shortcuts",
        "Độ dày nét vẽ": "Stroke width",
        "Ảnh vừa chụp": "Recent captures",
        "Ảnh vừa chụp sẽ xuất hiện ở đây trong phiên làm việc này.": "Captures from this session will appear here.",
        "Đang chụp: %@…": "Capturing %@…",
        "Đã chụp %@ · %@": "Captured %@ · %@",
        "Đã chụp cuộn · %@": "Scrolling capture complete · %@",
        "Đã mở %@": "Opened %@",
        "Đã mở ảnh %@": "Opened %@ capture",
        "Đã thêm %@": "Added %@",
        "Đã cắt ảnh còn %@": "Cropped image to %@",
        "Đã tải ảnh lên Google Drive: %@": "Uploaded image to Google Drive: %@",
        "Đã lưu %@": "Saved %@",
        "Mặc định: %@": "Default: %@",
        "Không thể khởi động lại: %@": "Could not restart: %@",
        "Không thể cập nhật Keychain (%d).": "Could not update Keychain (%d).",
        "Không thể lưu vào Keychain (%d).": "Could not save to Keychain (%d).",
        "Đã kết nối thư mục %@": "Connected to folder %@",
        "Khởi động": "Startup",
        "Mở Sharedee Tools khi đăng nhập": "Open Sharedee Tools at login",
        "Tính năng này cần macOS 13 trở lên.": "This feature requires macOS 13 or later.",
        "macOS cần bạn cho phép Sharedee Tools trong Mục đăng nhập.": "macOS needs you to allow Sharedee Tools in Login Items.",
        "Mở Mục đăng nhập…": "Open Login Items…",
        "App sẽ tự chạy trên thanh menu mỗi khi bạn bật máy và đăng nhập.": "The app starts in the menu bar whenever you turn on your Mac and log in.",
        "Không thể cập nhật mục đăng nhập: %@": "Could not update the login item: %@",
        "Cách tạo OAuth Client ID": "How to create an OAuth Client ID",
        "Xem hướng dẫn từng bước (khoảng 5 phút)": "Show step-by-step guide (about 5 minutes)",
        "Tạo project Google Cloud": "Create a Google Cloud project",
        "Đăng nhập Google Cloud Console, tạo project mới (ví dụ: Sharedee Tools) và chọn project đó ở thanh trên cùng.": "Sign in to Google Cloud Console, create a new project (for example, Sharedee Tools), and select it in the top bar.",
        "Tạo project": "Create project",
        "Bật Google Drive API": "Enable the Google Drive API",
        "Mở trang Google Drive API và bấm Enable. App dùng API này để tạo thư mục và tải ảnh lên.": "Open the Google Drive API page and click Enable. The app uses it to create folders and upload images.",
        "Mở Google Drive API": "Open Google Drive API",
        "Bật Google Picker API": "Enable the Google Picker API",
        "Mở trang Google Picker API và bấm Enable. API này cho phép chọn thư mục Drive có sẵn.": "Open the Google Picker API page and click Enable. It lets you choose an existing Drive folder.",
        "Mở Google Picker API": "Open Google Picker API",
        "Cấu hình màn hình đồng ý OAuth": "Configure the OAuth consent screen",
        "Trong Google Auth Platform, bấm Get started: nhập tên app và email hỗ trợ, chọn Audience là External, nhập email liên hệ rồi bấm Create.": "In Google Auth Platform, click Get started: enter an app name and support email, choose External as the audience, enter a contact email, then click Create.",
        "Mở Google Auth Platform": "Open Google Auth Platform",
        "Thêm tài khoản dùng thử": "Add test users",
        "Vào Audience → Test users → Add users và thêm email Google bạn sẽ đăng nhập. Khi app ở chế độ Testing, chỉ các email này được kết nối.": "Go to Audience → Test users → Add users and add the Google account you will sign in with. While the app is in Testing, only these accounts can connect.",
        "Mở Audience": "Open Audience",
        "Tạo OAuth Client ID loại Desktop app": "Create a Desktop app OAuth Client ID",
        "Mở Clients": "Open Clients",
        "Dán Client ID vào app": "Paste the Client ID into the app",
        "Mẹo: ở chế độ Testing, Google yêu cầu đăng nhập lại sau 7 ngày. Để kết nối lâu dài, vào Audience và bấm Publish app. Quyền drive.file mà app dùng không cần Google xét duyệt.": "Tip: in Testing mode, Google requires signing in again after 7 days. For a lasting connection, go to Audience and click Publish app. The drive.file scope this app uses does not require Google verification.",
        "Tài khoản Google": "Google account",
        "Xóa Client ID đã lưu?": "Remove the saved Client ID?",
        "Google Drive sẽ bị ngắt kết nối. Bạn có thể nhập lại Client ID bất cứ lúc nào.": "Google Drive will be disconnected. You can enter a Client ID again at any time.",
        "Sửa": "Edit",
        "Dùng Client ID tích hợp sẵn trong app": "Using the Client ID built into the app",
        "Đổi sang Client ID khác sẽ ngắt kết nối Google Drive hiện tại.": "Switching to a different Client ID disconnects the current Google Drive connection.",
        "Đang kiểm tra với Google…": "Checking with Google…",
        "Client ID hợp lệ.": "Client ID is valid.",
        "Sai định dạng. Client ID phải kết thúc bằng .apps.googleusercontent.com và không có khoảng trắng.": "Invalid format. A Client ID ends with .apps.googleusercontent.com and contains no spaces.",
        "Google không tìm thấy Client ID này. Hãy kiểm tra lại hoặc tạo Client ID mới.": "Google could not find this Client ID. Check it or create a new one.",
        "Client ID tồn tại nhưng không phải loại Desktop app. Hãy tạo Client ID mới với Application type là Desktop app.": "This Client ID exists but is not a Desktop app client. Create a new Client ID with Desktop app as the application type.",
        "Không kiểm tra được với Google (có thể do mạng). Vẫn có thể lưu và thử kết nối.": "Could not check with Google (possibly a network issue). You can still save it and try connecting.",
        "Đang chờ bạn đăng nhập trong trình duyệt…": "Waiting for you to sign in in your browser…",
        "Đăng nhập Google và cấp quyền. App sẽ tạo thư mục Sharedee Tools trên Drive.": "Sign in to Google and grant access. The app will create a Sharedee Tools folder on Drive.",
        "Vào Clients → Create client, chọn Application type là Desktop app, đặt tên rồi bấm Create. Sao chép Client ID (…apps.googleusercontent.com) và Client secret (GOCSPX-…).": "Go to Clients → Create client, choose Desktop app as the application type, name it, and click Create. Copy the Client ID (…apps.googleusercontent.com) and the Client secret (GOCSPX-…).",
        "Dán Client ID và Client secret vào các ô phía trên, đợi cả hai hiện dấu tích xanh, bấm Lưu Client ID, rồi bấm Kết nối Google Drive và cấp quyền trong trình duyệt.": "Paste the Client ID and Client secret into the fields above, wait for both green check marks, click Save Client ID, then click Connect Google Drive and grant access in your browser.",
        "Hãy nhập client secret của OAuth Client ID loại Desktop app.": "Enter the client secret of your Desktop app OAuth Client ID.",
        "Thiếu client secret. Bấm Sửa để nhập client secret của Client ID này.": "Client secret is missing. Click Edit to enter the client secret for this Client ID.",
        "Client ID và client secret đã lưu trong Keychain": "Client ID and client secret saved in Keychain",
        "Client secret (GOCSPX-…)": "Client secret (GOCSPX-…)",
        "Đang kiểm tra client secret…": "Checking client secret…",
        "Client secret khớp với Client ID.": "Client secret matches the Client ID.",
        "Client secret không khớp với Client ID này. Hãy sao chép lại từ Google Cloud.": "This client secret does not match the Client ID. Copy it again from Google Cloud.",
        "Chưa kiểm tra được client secret. Vẫn có thể lưu và thử kết nối.": "Could not check the client secret. You can still save it and try connecting.",
        "Dán client secret của cùng Client ID (trong trang chi tiết client trên Google Cloud).": "Paste the client secret of the same Client ID (on the client's details page in Google Cloud).",
        "Chưa kết nối được Google Drive": "Google Drive is not connected",
        "Sharedee Tools đã nhận quyền truy cập. Tab này sẽ tự đóng; nếu không, bạn có thể đóng nó và quay lại app.": "Sharedee Tools received access. This tab will close itself; if it doesn't, you can close it and return to the app.",
        "Đăng nhập đã bị hủy hoặc bị từ chối. Hãy quay lại Sharedee Tools để thử lại.": "Sign-in was cancelled or denied. Return to Sharedee Tools to try again.",
        "Thư mục Drive": "Drive folder",
        "Ảnh chụp sẽ được tải vào đây": "Captures upload here",
        "Thư mục của app": "App folders",
        "Tải lại danh sách": "Reload list",
        "Chưa có thư mục nào. Hãy tạo thư mục mới hoặc chọn từ Google Drive.": "No folders yet. Create a new folder or choose one from Google Drive.",
        "Tên thư mục mới": "New folder name",
        "Trong \"%@\"": "In \"%@\"",
        "thư mục hiện tại": "current folder",
        "Tạo thư mục": "Create folder",
        "Chọn thư mục khác trên Google Drive…": "Choose another folder on Google Drive…",
        "Hoặc dán link thư mục (tuỳ chọn)": "Or paste a folder link (optional)",
        "Cửa sổ chọn của Google không tạo được thư mục mới và sẽ yêu cầu đăng nhập lại. Muốn tạo thư mục bên trong một thư mục có sẵn, hãy chọn thư mục đó trước rồi tạo thư mục mới ở trên.": "Google's picker cannot create folders and asks you to sign in again. To create a folder inside an existing one, choose that folder first, then create the new folder above.",
        "Ảnh sẽ được tải vào thư mục %@": "Images will upload to %@",
        "Đã tạo thư mục %@": "Created folder %@",
        "Đang tải lên Google Drive…": "Uploading to Google Drive…",
        "Đã tải lên Google Drive": "Uploaded to Google Drive",
        "Đang tải…": "Uploading…",
        "Mở": "Open",
        "Mở ảnh trên Google Drive": "Open image in Google Drive",
        "Thử lại": "Retry",
        "Phiên bản %@ (%@)": "Version %@ (%@)",
        "Thông tin": "About",
        "Mã nguồn mở theo giấy phép Apache 2.0": "Open source under the Apache License 2.0",
        "Báo lỗi / góp ý ↗": "Report an issue ↗",
        "Giấy phép ↗": "License ↗",
        "Giới thiệu Sharedee Tools": "About Sharedee Tools",
        "Kéo để chọn vùng có chữ": "Drag to select an area with text",
        "Đã sao chép %ld dòng chữ": "Copied %ld lines of text",
        "Đã sao chép 1 dòng chữ": "Copied 1 line of text",
        "Không tìm thấy chữ trong vùng đã chọn": "No text found in the selected area",
        "Không nhận dạng được chữ": "Could not recognize text",
        "Chọn chữ trên ảnh (Live Text)": "Select text in the image (Live Text)",
        "Đang tìm chữ trong ảnh…": "Looking for text in the image…",
        "Bôi đen chữ trên ảnh để sao chép một phần.": "Select text in the image to copy part of it.",
        "Sao chép toàn bộ chữ": "Copy all text",
        "Xong": "Done",
        "Không thể chụp vùng đã chọn.": "Could not capture the selected area.",
        "Cuộn chậm lại một chút để ảnh ghép khớp.": "Scroll a little slower so the frames line up.",
        "Tự cuộn cần quyền Trợ năng. Bạn vẫn có thể tự cuộn bằng chuột.": "Auto-scroll needs Accessibility permission. You can still scroll with your mouse or trackpad.",
        "Kéo để chọn vùng cần chụp cuộn · Esc để hủy": "Drag to select the area to scroll-capture · Esc to cancel",
        "Đã ghép %@ px": "Stitched %@ px",
        "Kéo lại để đổi vùng": "Drag again to change the area",
        "Chụp": "Capture",
        "Cuộn trong vùng chọn, hoặc bấm Tự cuộn.": "Scroll inside the area, or click Auto-scroll.",
        "Dừng tự cuộn": "Stop auto-scroll",
        "Tự cuộn": "Auto-scroll",
        "Chiều dài tối đa": "Maximum length",
        "%@ px": "%@ px",
        "Kéo chọn vùng, bấm Chụp rồi tự cuộn bằng chuột hoặc bấm Tự cuộn trong vùng chọn. Tự cuộn cần quyền Trợ năng.": "Drag to select an area, click Capture, then scroll with your mouse or click Auto-scroll inside the area. Auto-scroll needs Accessibility permission.",
        "Chọn vùng, cuộn tay hoặc tự cuộn rồi ghép thành ảnh dài": "Select an area, scroll by hand or automatically, and stitch one tall image",
        "Nội dung thay đổi liên tục nên không ghép được. Hãy tạm dừng video hoặc cuộn bằng tay.": "The content keeps changing, so frames cannot be matched. Pause any video or scroll by hand.",
        "Đặt con trỏ chuột lên phần nội dung cần cuộn trong vùng chọn.": "Point at the content you want to scroll inside the area.",
        "Tự cuộn tại vị trí con trỏ chuột. Đặt chuột lên nội dung cần cuộn.": "Auto-scroll scrolls where the pointer is. Point at the content you want to scroll.",
        "Chụp màn hình": "Screenshot",
        "Thoát ứng dụng": "Quit Apps",
        "Không có ứng dụng nào đang mở": "No apps are open",
        "Thoát tất cả (%ld)": "Quit All (%ld)",
        "Thoát %ld ứng dụng đã chọn": "Quit %ld Selected Apps",
        "Chọn %@": "Select %@",
        "node_modules cũ": "Old node_modules",
        "Bộ cài đặt": "Installers",
        "Bản sao lưu iPhone, iPad": "iPhone & iPad backups",
        "Project không đụng tới hơn 30 ngày · cài lại bằng npm install": "Projects untouched for 30+ days · reinstall with npm install",
        "File .dmg, .pkg, .xip trong Downloads · chuyển vào Thùng rác": ".dmg, .pkg and .xip files in Downloads · moved to the Trash",
        "Bản sao lưu thiết bị trên máy này · chuyển vào Thùng rác": "Device backups stored on this Mac · moved to the Trash",
        "%@ / node_modules": "%@ / node_modules",
        "Đang chạy: %@": "Running: %@",
        "Thoát trước khi dọn": "Quit before cleaning",
        "Đã dùng %@ / %@": "%@ of %@ used",
        "Dọn phần đã chọn sẽ trống thêm %@": "Cleaning the selection frees %@",
        "Gỡ ứng dụng": "Uninstall",
        "Chọn ứng dụng để gỡ…": "Choose an App to Uninstall…",
        "Gỡ ứng dụng cùng các file nó để lại trong Thư viện": "Remove apps together with the files they leave in your Library",
        "Tên": "Name",
        "Dung lượng": "Size",
        "Lần dùng cuối": "Last used",
        "Tìm ứng dụng": "Search apps",
        "Kéo một ứng dụng vào đây để gỡ": "Drop an app here to uninstall it",
        "Đang tìm ứng dụng…": "Finding apps…",
        "ỨNG DỤNG · %ld": "APPS · %ld",
        "Chưa rõ lần dùng cuối": "Last use unknown",
        "Dùng lần cuối %@": "Last used %@",
        "Tất cả ứng dụng": "All apps",
        "Phiên bản %@": "Version %@",
        "FILE SẼ ĐƯỢC GỠ": "FILES TO REMOVE",
        "Không tìm thấy file sót lại": "No leftover files found",
        "Mọi thứ được chuyển vào Thùng rác, bạn vẫn khôi phục được.": "Everything goes to the Trash, so you can still restore it.",
        "Gỡ cài đặt · %@": "Uninstall · %@",
        "Khớp theo tên": "Name match",
        "Chỉ trùng tên thư mục, có thể thuộc ứng dụng khác. Hãy kiểm tra trước khi chọn.": "Only the folder name matches, so it may belong to another app. Check it before selecting.",
        "Đang gỡ %@…": "Uninstalling %@…",
        "Đã gỡ %@": "Uninstalled %@",
        "Mở Thùng rác": "Open Trash",
        "Gỡ ứng dụng khác": "Uninstall Another App",
        "Không thể gỡ ứng dụng này. Ứng dụng của macOS được hệ thống bảo vệ.": "This app can't be uninstalled. Apps that come with macOS are protected.",
        "%@ vẫn đang chạy. Hãy thoát ứng dụng rồi thử lại.": "%@ is still running. Quit it and try again.",
        "Không thể chuyển %@ vào Thùng rác. macOS có thể đã chặn thao tác này.": "Couldn't move %@ to the Trash. macOS may have blocked it.",
        "Bộ nhớ đệm ứng dụng": "App caches",
        "Nhật ký hệ thống": "Logs",
        "Dữ liệu Xcode": "Xcode data",
        "Bộ nhớ đệm lập trình": "Developer caches",
        "Thùng rác": "Trash",
        "File lớn": "Large files",
        "Ứng dụng sẽ tự tạo lại khi cần": "Apps rebuild these when needed",
        "Nhật ký và báo cáo lỗi cũ": "Old logs and crash reports",
        "DerivedData, DeviceSupport, cache simulator": "DerivedData, DeviceSupport, simulator caches",
        "npm, Gradle, Yarn, Bun": "npm, Gradle, Yarn, Bun",
        "Xoá vĩnh viễn các mục trong Thùng rác": "Permanently delete what's in the Trash",
        "Từ 200 MB trong Downloads, Desktop, Documents, Movies · chuyển vào Thùng rác": "200 MB or more in Downloads, Desktop, Documents, Movies · moved to the Trash",
        "Sẵn sàng quét": "Ready to scan",
        "Đang quét…": "Scanning…",
        "đã chọn để dọn": "selected to clean",
        "Đang dọn…": "Cleaning…",
        "đã được giải phóng": "freed up",
        "Tìm bộ nhớ đệm, nhật ký, dữ liệu Xcode và file lớn có thể dọn": "Find caches, logs, Xcode data, and large files you can clean up",
        "Tìm thấy %@ · chọn mục cần dọn bên dưới": "Found %@ · choose what to clean below",
        "Đang dọn %@": "Cleaning %@",
        "Máy của bạn đã gọn gàng hơn": "Your Mac is tidier now",
        "%ld mục không xoá được vì đang được dùng hoặc được hệ thống bảo vệ": "%ld items could not be removed because they are in use or protected by macOS",
        "Quét": "Scan",
        "Dừng": "Stop",
        "Quét lại": "Scan Again",
        "Dọn dẹp %@": "Clean Up %@",
        "KẾT QUẢ": "RESULTS",
        "Cần quyền Truy cập toàn bộ ổ đĩa": "Needs Full Disk Access",
        "Mở Cài đặt": "Open Settings",
        "Xem chi tiết": "Show details",
        "Sạch": "Clean",
        "Hiện trong Finder": "Show in Finder",
        "và %ld mục nhỏ hơn": "and %ld smaller items",
        "Dọn dẹp": "Cleanup",
        "Đang quét… %@": "Scanning… %@",
        "Đang dọn… %@": "Cleaning… %@",
        "Có thể dọn %@": "%@ can be cleaned",
        "Đã giải phóng %@": "Freed %@",
        "Quét rác ngay": "Scan Now",
        "Mở Dọn dẹp…": "Open Cleanup…",
        "Quét và dọn các file tạm để lấy lại dung lượng ổ đĩa": "Scan and remove temporary files to get disk space back",
        "Thoát": "Quit",
        "ẢNH GẦN ĐÂY": "RECENT CAPTURES",
        "Thoát %@": "Quit %@",
        "Thoát tất cả": "Quit All",
        "Thoát đã chọn (%ld)": "Quit Selected (%ld)",
        "ĐANG MỞ · %ld": "RUNNING · %ld",
        "Ứng dụng đang chạy sẽ xuất hiện ở đây.": "Running apps will appear here.",
        "Đóng nhanh các ứng dụng đang mở mà không cần khởi động lại máy": "Quickly close open apps without restarting your Mac"
    ]
}
